{
  "message": "An exception occurred during this request",
  "lineno": 28,
  "filename": "app.py",
  "exception": "connection closed,connection closed,connection closed",
  "stack_trace": "Traceback (most recent call last):\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 156, in __call__\n    await self.app(scope, receive, _send)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/exceptions.py\", line 73, in __call__\n    raise exc from None\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/exceptions.py\", line 62, in __call__\n    await self.app(scope, receive, sender)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/routing.py\", line 590, in __call__\n    await route(scope, receive, send)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/routing.py\", line 208, in __call__\n    await self.app(scope, receive, send)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/routing.py\", line 41, in app\n    response = await func(request)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/fastapi/routing.py\", line 129, in app\n    raw_response = await run_in_threadpool(dependant.call, **values)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/starlette/concurrency.py\", line 25, in run_in_threadpool\n    return await loop.run_in_executor(None, func, *args)\n  File \"/Users/lydia.stepanek/.pyenv/versions/3.7.3/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/Users/lydia.stepanek/mongo/selected-tests/src/selectedtests/app/controllers/project_task_mappings_controller.py\", line 77, in get\n    db.task_mappings(), parse_changed_files(changed_files), evg_project.identifier, threshold\n  File \"/Users/lydia.stepanek/mongo/selected-tests/src/selectedtests/task_mappings/get_task_mappings.py\", line 54, in get_correlated_task_mappings\n    {\"$project\": {\"_id\": False, \"tasks._id\": False, \"tasks.task_mapping_id\": False}},\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/collection.py\", line 2405, in aggregate\n    with self.__database.client._tmp_session(session, close=False) as s:\n  File \"/Users/lydia.stepanek/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py\", line 112, in __enter__\n    return next(self.gen)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/mongo_client.py\", line 1611, in _tmp_session\n    s = self._ensure_session(session)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/mongo_client.py\", line 1598, in _ensure_session\n    return self.__start_session(True, causal_consistency=False)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/mongo_client.py\", line 1551, in __start_session\n    server_session = self._get_server_session()\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/mongo_client.py\", line 1584, in _get_server_session\n    return self._topology.get_server_session()\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/topology.py\", line 434, in get_server_session\n    None)\n  File \"/Users/lydia.stepanek/Library/Caches/pypoetry/virtualenvs/selectedtests-jPCSPjxc-py3.7/lib/python3.7/site-packages/pymongo/topology.py\", line 200, in _select_servers_loop\n    self._error_message(selector))\npymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed\n",
  "logger": "selectedtests.app.app",
  "level": "error"
}